# Generated by Django 4.2.7 on 2023-11-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
