# Generated by Django 4.2.7 on 2023-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
