# Generated by Django 4.2.7 on 2023-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='title_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание ссылки'),
        ),
    ]
